### ISSUE TITLE
Fehler bei Upload mit Sonderzeichen

### ISSUE THREAD

**Issue by SuperTux88** [LambdaCast/LambdaCast#51]
<p>Traceback (most recent call last):</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response<br/>
    response = callback(request, *callback_args, **callback_kwargs)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view<br/>
    return view_func(request, *args, **kwargs)</p>

<p>  File "/data/srv/LambdaCast/portal/views.py", line 164, in submit<br/>
    cmodel = form.save()</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/forms/models.py", line 364, in save<br/>
    fail_message, commit, construct=False)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/forms/models.py", line 86, in save_instance<br/>
    instance.save()</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/base.py", line 463, in save<br/>
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/base.py", line 551, in save_base<br/>
    result = manager._insert(<span class="error">&#91;self&#93;</span>, fields=fields, return_id=update_pk, using=using, raw=raw)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/manager.py", line 203, in _insert<br/>
    return insert_query(self.model, objs, fields, **kwargs)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/query.py", line 1576, in insert_query<br/>
    return query.get_compiler(using=using).execute_sql(return_id)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 909, in execute_sql<br/>
    for sql, params in self.as_sql():</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 872, in as_sql<br/>
    for obj in self.query.objs</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/fields/files.py", line 249, in pre_save<br/>
    file.save(file.name, file, save=False)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/db/models/fields/files.py", line 86, in save<br/>
    self.name = self.storage.save(name, content)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/core/files/storage.py", line 44, in save<br/>
    name = self.get_available_name(name)</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/core/files/storage.py", line 70, in get_available_name<br/>
    while self.exists(name):</p>

<p>  File "/data/srv/LambdaCast/.venv/lib/python2.6/site-packages/django/core/files/storage.py", line 230, in exists<br/>
    return os.path.exists(self.path(name))</p>

<p>  File "/usr/lib/python2.6/genericpath.py", line 18, in exists<br/>
    st = os.stat(path)</p>

<p>UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 44: ordinal not in range(128)</p>
<i>[LAMBDA-49] created by benjamin</i>

**Comment by SuperTux88** [comment]
<p>Besteht dieser Fehler immernoch? Welche Sonderzeichen wurden eingetragen wo eingetragen?</p>
<i>by dennis</i>

**Comment by SuperTux88** [comment]
<p>Kann den Fehler mit dem originalen Dateinamen "test (Köpie).mp3" und Python 2.7 nicht reproduzieren.</p>
<i>by dennis</i>
